// 
// Auth:    zhgyee
// Date:    2020/4/1
// Mail:    zhgyee@gmail.com
// Disc:    This file a part of xreality

#ifndef XRCORE_XRAPIEXTENSION_H
#define XRCORE_XRAPIEXTENSION_H

#define XRAPI_TEXTURE_SWAPCHAIN_EXTERNAL_TEXTRUEID 0x3
#define XRAPI_DEFAULT_TEXTURE_SWAPCHAIN_BLACK 0xfe

#define XRAPI_SYS_PROP_BUILD_PRODUCT 130
#define XRAPI_SYS_PROP_LENS_SEPERATION 1024
#define XRAPI_SYS_PROP_WIDTH_METERS 1025
#define XRAPI_SYS_PROP_HEIGHT_METERS 1026
#define XRAPI_SYS_PROP_UNITY_VSYNC_CNT 1027
#define XRAPI_SYS_PROP_WFD_TYPE 1028
#define XRAPI_SYS_PROP_WFD_WHRATIO 1029
#define XRAPI_SYS_PROP_SCREEN_TYPE 1030
#define XRAPI_SYS_PROP_CHROMATIC_CORRECTION_STATE 1031
#define XRAPI_SYS_PROP_CHROMATIC_ABERRATION_0 1032
#define XRAPI_SYS_PROP_CHROMATIC_ABERRATION_1 1033
#define XRAPI_SYS_PROP_CHROMATIC_ABERRATION_2 1034
#define XRAPI_SYS_PROP_CHROMATIC_ABERRATION_3 1035

#define XRAPI_SCREEN_MODE 2048
#define XRAPI_SCREEN_MODE_DEFAULT 0
#define XRAPI_SCREEN_MODE_DUAL XRAPI_SCREEN_MODE_DEFAULT
#define XRAPI_SCREEN_MODE_SPLIT 1
#define XRAPI_SCREEN_MODE_MULTIVIEW 2

#define 	XRAPI_SET_USB_DEVICE_FD  100
#define 	XRAPI_SET_EXT_NATIVE_WINDOW  101

int xrapiInvoke(int invoke, void* val);

#endif //XRCORE_XRAPIEXTENSION_H
